### ISSUE TITLE
Ad block detected

### ISSUE THREAD

**Issue by EatVanced** [sureshchand12a/chp-ads-block-detector#1]
Ad block detected despite whitelisting the website.
Here in Indonesia, reddit is blocked, and https://chpadblock.com/ use ads.reddit.com to detect AdBlock. I can get around this by bypassing the government censorship, now my adblocker is working fine, i see no ads for your website. Very easy to bypass it but bypassing the government censorship is much harder than your "top one ad block detection".

Please fix it, thanks

**Comment by scthakuri** [comment]
We have changed the AdBlock detection system in our latest release. We use only google ads to detect the AdBlock.
